services:
  - type: web
    name: music-genre-classifier
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --workers 1 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: MODEL_CACHE_DIR
        value: /tmp
    plan: free
